[api]
port = 4000
path = '/graphql'
graphiql = true

[opentok]
apiKey = 'YOUR_API_KEY'
secret = 'YOUR_SECRET'

# See https://tokbox.com/developer/sdks/node/reference/OpenTok.html#createSession
# [opentok.sessionOptions]
# location = ''
# mediaMode = ''
# archiveMode = ''
