// flow-typed signature: f88e671b6c08d902419b56cf05f2abeb
// flow-typed version: <<STUB>>/opentok_v^2.6.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opentok'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opentok' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opentok/Gruntfile' {
  declare module.exports: any;
}

declare module 'opentok/lib/archiving' {
  declare module.exports: any;
}

declare module 'opentok/lib/callbacks' {
  declare module.exports: any;
}

declare module 'opentok/lib/client' {
  declare module.exports: any;
}

declare module 'opentok/lib/errors' {
  declare module.exports: any;
}

declare module 'opentok/lib/generateJwt' {
  declare module.exports: any;
}

declare module 'opentok/lib/moderation' {
  declare module.exports: any;
}

declare module 'opentok/lib/opentok' {
  declare module.exports: any;
}

declare module 'opentok/lib/session' {
  declare module.exports: any;
}

declare module 'opentok/lib/signaling' {
  declare module.exports: any;
}

declare module 'opentok/lib/sipInterconnect' {
  declare module.exports: any;
}

declare module 'opentok/sample/Archiving/index' {
  declare module.exports: any;
}

declare module 'opentok/sample/Archiving/public/js/host' {
  declare module.exports: any;
}

declare module 'opentok/sample/Archiving/public/js/participant' {
  declare module.exports: any;
}

declare module 'opentok/sample/HelloWorld/index' {
  declare module.exports: any;
}

declare module 'opentok/sample/HelloWorld/public/js/helloworld' {
  declare module.exports: any;
}

declare module 'opentok/sample/SipInterconnect/app' {
  declare module.exports: any;
}

declare module 'opentok/sample/SipInterconnect/config' {
  declare module.exports: any;
}

declare module 'opentok/spec/opentok_spec' {
  declare module.exports: any;
}

declare module 'opentok/test/callbacks-test' {
  declare module.exports: any;
}

declare module 'opentok/test/helpers' {
  declare module.exports: any;
}

declare module 'opentok/test/moderation-test' {
  declare module.exports: any;
}

declare module 'opentok/test/opentok-test' {
  declare module.exports: any;
}

declare module 'opentok/test/session-test' {
  declare module.exports: any;
}

declare module 'opentok/test/signaling-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opentok/Gruntfile.js' {
  declare module.exports: $Exports<'opentok/Gruntfile'>;
}
declare module 'opentok/lib/archiving.js' {
  declare module.exports: $Exports<'opentok/lib/archiving'>;
}
declare module 'opentok/lib/callbacks.js' {
  declare module.exports: $Exports<'opentok/lib/callbacks'>;
}
declare module 'opentok/lib/client.js' {
  declare module.exports: $Exports<'opentok/lib/client'>;
}
declare module 'opentok/lib/errors.js' {
  declare module.exports: $Exports<'opentok/lib/errors'>;
}
declare module 'opentok/lib/generateJwt.js' {
  declare module.exports: $Exports<'opentok/lib/generateJwt'>;
}
declare module 'opentok/lib/moderation.js' {
  declare module.exports: $Exports<'opentok/lib/moderation'>;
}
declare module 'opentok/lib/opentok.js' {
  declare module.exports: $Exports<'opentok/lib/opentok'>;
}
declare module 'opentok/lib/session.js' {
  declare module.exports: $Exports<'opentok/lib/session'>;
}
declare module 'opentok/lib/signaling.js' {
  declare module.exports: $Exports<'opentok/lib/signaling'>;
}
declare module 'opentok/lib/sipInterconnect.js' {
  declare module.exports: $Exports<'opentok/lib/sipInterconnect'>;
}
declare module 'opentok/sample/Archiving/index.js' {
  declare module.exports: $Exports<'opentok/sample/Archiving/index'>;
}
declare module 'opentok/sample/Archiving/public/js/host.js' {
  declare module.exports: $Exports<'opentok/sample/Archiving/public/js/host'>;
}
declare module 'opentok/sample/Archiving/public/js/participant.js' {
  declare module.exports: $Exports<'opentok/sample/Archiving/public/js/participant'>;
}
declare module 'opentok/sample/HelloWorld/index.js' {
  declare module.exports: $Exports<'opentok/sample/HelloWorld/index'>;
}
declare module 'opentok/sample/HelloWorld/public/js/helloworld.js' {
  declare module.exports: $Exports<'opentok/sample/HelloWorld/public/js/helloworld'>;
}
declare module 'opentok/sample/SipInterconnect/app.js' {
  declare module.exports: $Exports<'opentok/sample/SipInterconnect/app'>;
}
declare module 'opentok/sample/SipInterconnect/config.js' {
  declare module.exports: $Exports<'opentok/sample/SipInterconnect/config'>;
}
declare module 'opentok/spec/opentok_spec.js' {
  declare module.exports: $Exports<'opentok/spec/opentok_spec'>;
}
declare module 'opentok/test/callbacks-test.js' {
  declare module.exports: $Exports<'opentok/test/callbacks-test'>;
}
declare module 'opentok/test/helpers.js' {
  declare module.exports: $Exports<'opentok/test/helpers'>;
}
declare module 'opentok/test/moderation-test.js' {
  declare module.exports: $Exports<'opentok/test/moderation-test'>;
}
declare module 'opentok/test/opentok-test.js' {
  declare module.exports: $Exports<'opentok/test/opentok-test'>;
}
declare module 'opentok/test/session-test.js' {
  declare module.exports: $Exports<'opentok/test/session-test'>;
}
declare module 'opentok/test/signaling-test.js' {
  declare module.exports: $Exports<'opentok/test/signaling-test'>;
}
