// flow-typed signature: 659712d347e5459064a0f943ea48c0ef
// flow-typed version: <<STUB>>/toml-require_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toml-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toml-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toml-require/test' {
  declare module.exports: any;
}

declare module 'toml-require/test/index' {
  declare module.exports: any;
}

declare module 'toml-require/test/node_modules/toml/benchmark' {
  declare module.exports: any;
}

declare module 'toml-require/test/node_modules/toml/index' {
  declare module.exports: any;
}

declare module 'toml-require/test/node_modules/toml/lib/compiler' {
  declare module.exports: any;
}

declare module 'toml-require/test/node_modules/toml/lib/parser' {
  declare module.exports: any;
}

declare module 'toml-require/test/node_modules/toml/test/smoke' {
  declare module.exports: any;
}

declare module 'toml-require/test/node_modules/toml/test/test_toml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toml-require/index' {
  declare module.exports: $Exports<'toml-require'>;
}
declare module 'toml-require/index.js' {
  declare module.exports: $Exports<'toml-require'>;
}
declare module 'toml-require/test.js' {
  declare module.exports: $Exports<'toml-require/test'>;
}
declare module 'toml-require/test/index.js' {
  declare module.exports: $Exports<'toml-require/test/index'>;
}
declare module 'toml-require/test/node_modules/toml/benchmark.js' {
  declare module.exports: $Exports<'toml-require/test/node_modules/toml/benchmark'>;
}
declare module 'toml-require/test/node_modules/toml/index.js' {
  declare module.exports: $Exports<'toml-require/test/node_modules/toml/index'>;
}
declare module 'toml-require/test/node_modules/toml/lib/compiler.js' {
  declare module.exports: $Exports<'toml-require/test/node_modules/toml/lib/compiler'>;
}
declare module 'toml-require/test/node_modules/toml/lib/parser.js' {
  declare module.exports: $Exports<'toml-require/test/node_modules/toml/lib/parser'>;
}
declare module 'toml-require/test/node_modules/toml/test/smoke.js' {
  declare module.exports: $Exports<'toml-require/test/node_modules/toml/test/smoke'>;
}
declare module 'toml-require/test/node_modules/toml/test/test_toml.js' {
  declare module.exports: $Exports<'toml-require/test/node_modules/toml/test/test_toml'>;
}
