// flow-typed signature: e31d73642857e69e6e92fd0770c8737b
// flow-typed version: <<STUB>>/xtend_v^4.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xtend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xtend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xtend/immutable' {
  declare module.exports: any;
}

declare module 'xtend/mutable' {
  declare module.exports: any;
}

declare module 'xtend/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xtend/immutable.js' {
  declare module.exports: $Exports<'xtend/immutable'>;
}
declare module 'xtend/mutable.js' {
  declare module.exports: $Exports<'xtend/mutable'>;
}
declare module 'xtend/test.js' {
  declare module.exports: $Exports<'xtend/test'>;
}
